/**
 * This class is generated by jOOQ
 */
package test.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import test.jooq.tables.Author;
import test.jooq.tables.Book;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqDemo extends SchemaImpl {

	private static final long serialVersionUID = 634427889;

	/**
	 * The reference instance of <code>jooq_demo</code>
	 */
	public static final JooqDemo JOOQ_DEMO = new JooqDemo();

	/**
	 * No further instances allowed
	 */
	private JooqDemo() {
		super("jooq_demo");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Author.AUTHOR,
			Book.BOOK);
	}
}
