/**
 * This class is generated by jOOQ
 */
package test.jooq;


import javax.annotation.Generated;

import test.jooq.tables.Author;
import test.jooq.tables.Book;


/**
 * Convenience access to all tables in jooq_demo
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table jooq_demo.author
	 */
	public static final Author AUTHOR = test.jooq.tables.Author.AUTHOR;

	/**
	 * The table jooq_demo.Book
	 */
	public static final Book BOOK = test.jooq.tables.Book.BOOK;
}
